version: '3'
services:

    database:
        container_name: "db-${COMPOSE_PROJECT_NAME}"
        image: mariadb:10.4.12-bionic
        expose:
            - 3306
        restart: on-failure:5
        environment:
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

    wordpress:
        container_name: "wp-${COMPOSE_PROJECT_NAME}"
        image: "wordpress:${WORDPRESS_VERSION}-php7.4-apache"
        depends_on:
            - database
        ports:
            - "${WORDPRESS_HTTP_PORT}:80"
        restart: on-failure:5
        volumes:
            - ./public:/var/www/html
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
            WORDPRESS_DB_USER: "${MYSQL_USER}"
            WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"

    phpmyadmin:
        container_name: "admin-${COMPOSE_PROJECT_NAME}"
        image: "phpmyadmin/phpmyadmin:${PHPADMIN_VERSION}-fpm-alpine"
        depends_on:
            - wordpress
        ports:
            - "${PHPADMIN_PORT}:80"
        restart: on-failure:5
        environment:
            PMA_HOST: database

    wordmove:
        container_name: "wm-${COMPOSE_PROJECT_NAME}"
        image: welaika/wordmove:alpine
        tty: true
        depends_on:
            - wordpress
        restart: on-failure:5
        environment:
          WORDMOVE_SQL_ADAPTER: "${WORDMOVE_SQL_ADAPTER:-default}"
          LOCAL_DB_NAME: "${MYSQL_DATABASE}"
          LOCAL_DB_USER: "${MYSQL_USER}"
          LOCAL_DB_PASS: "${MYSQL_PASSWORD}"
          PRODUCTION_HOST: "${PRODUCTION_URL}"
          PRODUCTION_WP_PATH: "${PRODUCTION_WP_PATH}"
          PRODUCTION_DB_HOST: "${PRODUCTION_DB_HOST}"
          PRODUCTION_DB_PORT: "${PRODUCTION_DB_PORT}"
          PRODUCTION_DB_NAME: "${PRODUCTION_DB_NAME}"
          PRODUCTION_DB_USER: "${PRODUCTION_DB_USER}"
          PRODUCTION_DB_PASS: "${PRODUCTION_DB_PASS}"
          PRODUCTION_SSH_HOST: "${PRODUCTION_SSH_HOST}"
          PRODUCTION_SSH_PORT: "${PRODUCTION_SSH_PORT:-22}"
          PRODUCTION_SSH_USER: "${PRODUCTION_SSH_USER}"
        volumes:
            - ./config:/home
            - ./public:/var/www/html
            - ~/.ssh:/root/.ssh      # (!)

#######################################
#
# Se quiser atribuir nomes personalizados
# a cada um dos contêineres criados aqui, 
# insira a propriedade *container_name:* 
# no serviço do contêiner a ser renomeado.
#
# Esse procedimento será necessário caso
# você queira reutilizar este modelo de
# configuração para criar contêineres de
# outro projeto Wordpress e ambos precisem
# permanecer na sua máquina ao mesmo tempo.
#
# Para *rodar* dois projetos Wordpress ao
# mesmo tempo, também será necessário mudar
# a porta utilizada por cada contêiner do
# novo projeto.
#
# (!) Você pode copiar suas chaves SSH para
# a pasta SSH caso elas sejam necessárias
# para se conectar remotamente ao seu
# servidor de produção.
#
#######################################
