version: '3'
services:
    database:
        image: mysql:5.7
        ports:
            - "3307:3306"
        restart: on-failure:5
        environment:
            MYSQL_DATABASE: <insira_nome_do_banco>
            MYSQL_USER: <insira_usuario_do_wp_ao_banco>
            MYSQL_PASSWORD: <insira_senha_do_banco>
            MYSQL_ROOT_PASSWORD: <insira_senha_root_do_banco>
    wordpress:
        depends_on:
            - database
        image: wordpress:latest
        ports:
            - "8000:80"
        restart: on-failure:5
        volumes:
            - ./public:/var/www/html
        environment:
            WORDPRESS_DB_HOST: database:3306
            WORDPRESS_DB_NAME: <nome_do_banco>
            WORDPRESS_DB_USER: <usuario_do_banco>
            WORDPRESS_DB_PASSWORD: <senha_do_banco>
    phpmyadmin:
        depends_on:
            - wordpress
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        restart: on-failure:5
        environment:
            PMA_HOST: database
    wordmove:
        tty: true
        depends_on:
            - wordpress
        build: ./wordmove
        restart: on-failure:5
        volumes:
            - ./config:/home
            - ./public:/var/www/html
            - ~/.ssh:/root/.ssh      # (!)
#######################################
#
# Se quiser atribuir nomes personalizados
# a cada um dos contêineres criados aqui, 
# insira a propriedade *container_name:* 
# no serviço do contêiner a ser renomeado.
#
# Esse procedimento será necessário caso
# você queira reutilizar este modelo de
# configuração para criar contêineres de
# outro projeto Wordpress e ambos precisem
# permanecer na sua máquina ao mesmo tempo.
#
# Para *rodar* dois projetos Wordpress ao
# mesmo tempo, também será necessário mudar
# a porta utilizada por cada contêiner do
# novo projeto.
#
# (!) Você pode copiar suas chaves SSH para
# a pasta SSH caso elas sejam necessárias
# para se conectar remotamente ao seu
# servidor de produção.
#
#######################################
